In [8]:
# include the parent dir into pythonpath
import sys
sys.path.append('..')

from src.dataset.dataloader import load_data, HEPTorchDataset
from time import time

dataloader, class_weights = load_data("minerva_1A", "/global/cfs/cdirs/m3246/gregork/Minerva/20260201_all_max_blobs_and_prongs_split_fix_anomalies", batch=1024, dataset_type="train", mode="regression", distributed=False, classification_event_type=False, use_cond=True)

sample = next(iter(dataloader))



Number of events per file [6080324]
Number of events per file [6080324]
Number of events per file [6080324]
Number of events per file [6080324]


In [9]:
sample.keys()

dict_keys(['X', 'y', 'attention_mask', 'cond', 'pid', 'add_info', 'data_pid', 'vertex_pid'])

In [10]:
sample["y"]

tensor([1.6565, 1.4380, 1.6914,  ..., 1.7839, 2.6800, 1.2858])

In [11]:
sample["X"][0].shape

torch.Size([33, 5])

In [12]:
len(dataloader)

Number of events per file [6080324]


5938

In [13]:
sample["cond"]

tensor([[  5.5935, -11.5129,   8.2612,   7.9832],
        [-11.5129, -11.5129,   4.2542,   3.8549],
        [  3.9747, -11.5129, -11.5129, -11.5129],
        ...,
        [  3.3407, -11.5129,   6.5784,   6.2545],
        [  4.1543, -11.5129,   8.2818,   8.0038],
        [  2.1174, -11.5129,   4.9320,   4.5327]])

In [15]:
sample["attention_mask"]

tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.]])